version: '3.3'

services:
  web:
    build: .  # Build the Docker image using the Dockerfile in the current directory
    command: python manage.py runserver 0.0.0.0:8000  # Start the Django development server
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "8000:8000"  # Expose port 8000 to the host machine
